// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE9J18RiJQkK1P74EfQidUN1Ecosx5L6c',
    appId: '1:1090949559312:web:aff76426f98e913fb24695',
    messagingSenderId: '1090949559312',
    projectId: 'tugassolo',
    authDomain: 'tugassolo.firebaseapp.com',
    storageBucket: 'tugassolo.appspot.com',
    measurementId: 'G-L2N412P748',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClx0_qazqdt1yEQHTe3WwAgZyIgPfv_Yg',
    appId: '1:1090949559312:android:7c6a6680820ed7b5b24695',
    messagingSenderId: '1090949559312',
    projectId: 'tugassolo',
    storageBucket: 'tugassolo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBZ8lkcjPEX-ZJZ4MhxNlLqCg3RFhwOUk',
    appId: '1:1090949559312:ios:c937256c2c559f18b24695',
    messagingSenderId: '1090949559312',
    projectId: 'tugassolo',
    storageBucket: 'tugassolo.appspot.com',
    iosBundleId: 'com.example.tes1',
  );

}